#docker-compose.yml
version: '3.8'

services:
    frontend: 
      build: 
        context: ./services/frontend
        dockerfile: Dockerfile
      ports:
        - 5173:5173
#      volumes: 
#        - ./services/frontend:/app

    backend:
      build:
        context: ./services/backend
        dockerfile: Dockerfile
      ports:
        - 7000:7000
#      volumes:
#        - ./services/backend:/app

    
